# Generated by Django 4.0.5 on 2022-06-30 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_remove_blogpost_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='chakras',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
